### ISSUE TITLE
Plot on preexisting Axes

### ISSUE THREAD

**Issue by adamvis** [erdogant/kaplanmeier#10]
At the moment "plot" method directly plots stdout. It would be better to accept an ax parameter (as for pandas) to direct plot output to

**Comment by erdogant** [comment]
Agree. I created a update. The new version can have an ax as input parameter now.
`pip install -U kaplanmeier
`
```
import kaplanmeier as km
# Example data
df = km.example_data()
# Fit
results = km.fit(df['time'], df['Died'], df['group'])
# Plot
fig, ax = km.plot(results)
fig, ax = km.plot(results, ax=ax)

```

**Comment by adamvis** [comment]
Thanks for the update!
