### ISSUE TITLE
Avoid creating an axes (of a figure) many times in the loops & remove mishandled `subplots_adjust`

### ISSUE THREAD

**Issue by neikxd** [erdogant/kaplanmeier#2]
When plot with `km.plot(out, methodtype='custom')`

- An axes was created many time, then got warning: 

`kaplanmeier.py:301: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111)`

Please move it up out of the loops:

```python
ax = fig.add_subplot(111)
for k in range(0,len(KMcoord)):
        KM=KMcoord[k]
```

- `kaplanmeier.py:302-304` > **subplots_adjust** make the plot out of range and mishandled. Please remove them.

**Comment by erdogant** [comment]
Thanks for pointing out!
I updated the library with your suggested fix. 

Update with:
`
pip install -U kaplanmeier
`
