### ISSUE TITLE
Documentation does not match code, possibly incorrect handling of logrank=[]

### ISSUE THREAD

**Issue by shusheer** [erdogant/kaplanmeier#5]
Nice project - I got my data processed and plotted in less than an hour from google pointing me to this project.

Bug 1: The documentation seems to be a little out of date though. Specifically, kaplanmeier/kaplanmeier.py lines 185...191 show that CI lines should preferably text descriptions of the line type, and that this should not be None when we actually want to show them, whereas the code example (but not the actual plot) for CI lines sets this to None. The code example also stores the result as "result", but later refers to "out", which may confuse people when just running the code and expecting it to work.

Bug 2: The title for km.plot always appends the logrank p-value, which is not always desired. It appears that at kaplanmeier/kaplanmeier.py line 181 you may have intended the ability to disable this by setting logrank=[] - but in this case the whole plot would not be plotted. I wonder if you meant to use this to alter the title format string?

**Comment by erdogant** [comment]
I created a new update tackling these issues.
Sphinx pages are updated. Check out [here](https://erdogant.github.io/kaplanmeier/pages/html/index.html).

update with: `pip install -U kaplanmeier`
Version should be >= 0.1.7

```
from kaplanmeier import kaplanmeier as km
df = km.example_data()
results = km.fit(df['time'], df['Died'], df['group'])

```
```
# Custom title
km.plot(results, title='Custom title text')

```

![image](https://user-images.githubusercontent.com/31008129/172120424-62e211c3-5c6f-439e-821b-ff4dcf42b55e.png)

```
# Defaults
km.plot(results)
km.plot(results, title=None)

```

![image](https://user-images.githubusercontent.com/31008129/172120616-678813a9-217b-4954-9819-ab15b23b01f0.png)

```
# No title
km.plot(results)
km.plot(results, title='')

```
![image](https://user-images.githubusercontent.com/31008129/172120701-dd3c8f6f-11c0-47ce-9ff4-84b13b33485b.png)

**Comment by shusheer** [comment]
Nice work!
