### ISSUE TITLE
Ability to relocate the legend plotted

### ISSUE THREAD

**Issue by vc1492a** [erdogant/kaplanmeier#7]
In some cases, the legend gets placed in the center of the chart and obscures the view. 

It would be nice to have the ability to disable the legend completely or to indicate where it would be placed, e.g. `lower right`. 

I tried using `matplotlib.pyplot` to manipulate the plot, but no luck: 

```python
import kaplanmeier as km
import matplotlib.pyplot as plt 

plt.legend(loc='lower right')
km.plot(
    mission_name_results,
    cmap='Set1', 
    cii_lines='lifelines',
    cii_alpha=0.05,
    methodtype='lifeline'
)
```

This results in two separate plots.

**Comment by vc1492a** [comment]
Sent $10 your way 😉

**Comment by erdogant** [comment]
Thanks mate! Update to the latest version with:

`pip install -U kaplanmeier
`
You should only use the location code and not the string, see [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html).

```
# Examples
import kaplanmeier as km
df = km.example_data()
results = km.fit(df['time'], df['Died'], df['group'])
km.plot(results, title='Custom title text', legend=1)
km.plot(results, title='Custom title text', legend=2)

```

**Comment by vc1492a** [comment]
Thanks for the quick update 🚀  can confirm a stable, working release.
