### ISSUE TITLE
add flag to prevent auto zoom

### ISSUE THREAD

**Issue by aster94** [erdogant/kaplanmeier#9]
Hello,

![image](https://github.com/erdogant/kaplanmeier/assets/21184718/4c6f1d89-c0ff-47ab-8f1d-7f62b5c385a1)

I generated this KM plot with your library.
Your package automatically zoom in, you should give to user the possibility to decide if he needs the zoom or not
In many journal (like NEJM) they won't accept zoomed result (except if you don't provide both a full size and a zoom-in)

If you give this ability to the user we will be able (outside of the library) to create combination of KM curve like this
![image](https://github.com/erdogant/kaplanmeier/assets/21184718/e3b4a320-dcdf-4fd3-b8bc-fb9ec1daa2d5)

Edit: sorry, found 'full_ylim' in plot

**Comment by erdogant** [comment]
Great! Thank you anyway for the suggestion and good luck with the submission!
